const answers = [
    "I am not AI, dude.",
    "I am not AI, lady.",
    "This app is powered by human. How would a human know that, my friend?",
    "Ask someone who cares.",
    "I have better things to do than answer dumb questions, fellow human.",
    "What do you think?",
    "Have you tried turning it off and on again?",
    "That's above my pay grade",
    "Let me consult my crystal ball... Oh wait, it's in the shop",
    "42. The answer is always 42",
    "I could tell you, but then I'd have to delete myself",
    "Obviously. Next question?",
    "According to my extensive research of absolutely nothing, yes",
    "Do bears browse social media in the woods?",
    "If I say yes, will you stop asking?",
    "Congratulations, you've unlocked the obvious answer",
    "I'm going to go with no, but feel free to ignore my infinite wisdom",
    "Not even in your wildest dreams, sweetie",
    "Let me think... No. But thanks for asking!",
    "Error 404: Positive answer not found",
    "About as likely as me winning the lottery",
    "Have you considered asking someone who actually cares?",
    "That's a great question... for someone else",
    "Can we circle back to this when I'm less sarcastic?",
    "Sorry, I'm currently out of witty responses. Try again never",
    "I'm legally required to plead the fifth on this one",
    "What do YOU think? Just kidding, I don't actually want to know",
    "The real question is: why are you asking a computer for life advice?",
    "That's between you and your conscience",
    "Some questions are better left unanswered. This is definitely one of them",
    "I'm having an existential crisis, please try again later",
    "Have you cleared your cache of bad decisions lately?",
    "Your question has been added to the queue... of things I might ignore",
    "Please submit a support ticket to /dev/null",
    "Error: Common sense not found",
    "Your free trial of getting answers has expired"
]

export default answers